import type { Profile } from "./types"

export const mockProfiles: Profile[] = [
  {
    id: "1",
    user_id: "1",
    name: "Ana Silva",
    age: 28,
    bio: "Desenvolvedora Full Stack apaixonada por tecnologia. Procurando networking e parcerias para projetos inovadores.",
    location: "São Paulo, SP",
    photos: ["/professional-woman-developer.png"],
    interests: ["Tecnologia", "Startups", "Café", "Viagens"],
    connection_types: ["networking", "business", "friendship"],
    occupation: "Software Engineer",
    company: "Tech Corp",
    skills: ["React", "Node.js", "TypeScript", "AWS"],
    looking_for: ["Parceiros de negócios", "Networking", "Amizades"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    user_id: "2",
    name: "Carlos Mendes",
    age: 32,
    bio: "Empreendedor e investidor. Sempre em busca de novas ideias e pessoas talentosas para colaborar.",
    location: "Rio de Janeiro, RJ",
    photos: ["/professional-entrepreneur.png"],
    interests: ["Empreendedorismo", "Investimentos", "Esportes", "Música"],
    connection_types: ["business", "networking"],
    occupation: "CEO & Founder",
    company: "StartupXYZ",
    skills: ["Gestão", "Vendas", "Marketing", "Finanças"],
    looking_for: ["Investidores", "Co-founders", "Desenvolvedores"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    user_id: "3",
    name: "Mariana Costa",
    age: 25,
    bio: "Designer UX/UI criativa. Adoro conhecer pessoas novas e trocar experiências sobre design e arte.",
    location: "Belo Horizonte, MG",
    photos: ["/creative-woman-designer.png"],
    interests: ["Design", "Arte", "Fotografia", "Yoga"],
    connection_types: ["friendship", "creative", "networking"],
    occupation: "UX/UI Designer",
    company: "Design Studio",
    skills: ["Figma", "Adobe XD", "Illustrator", "User Research"],
    looking_for: ["Amizades", "Parceiros criativos", "Networking"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    user_id: "4",
    name: "Pedro Santos",
    age: 30,
    bio: "Product Manager com experiência em tech. Procurando conexões profissionais e novas amizades.",
    location: "São Paulo, SP",
    photos: ["/professional-product-manager.png"],
    interests: ["Produto", "Tecnologia", "Corrida", "Leitura"],
    connection_types: ["networking", "friendship", "sports"],
    occupation: "Product Manager",
    company: "Big Tech Co",
    skills: ["Product Strategy", "Agile", "Data Analysis", "Leadership"],
    looking_for: ["Networking", "Amigos para correr", "Mentoria"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    user_id: "5",
    name: "Julia Oliveira",
    age: 27,
    bio: "Marketing digital e growth hacking. Sempre animada para conhecer pessoas e trocar ideias sobre negócios.",
    location: "Curitiba, PR",
    photos: ["/professional-woman-marketing.png"],
    interests: ["Marketing", "Growth", "Viagens", "Gastronomia"],
    connection_types: ["networking", "business", "friendship", "dating"],
    occupation: "Growth Marketing Manager",
    company: "Scale Up Inc",
    skills: ["SEO", "Google Ads", "Analytics", "Content Marketing"],
    looking_for: ["Networking", "Parcerias", "Novas conexões"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
